using System.Threading.Tasks;
using VerifyXunit;
using Xunit;

[UsesVerify]
public class GeneratorSnapshotsTests
{
    [Fact]
    public Task MinimalGrammar_GeneratesExpected()
    {
        // NOTE: This test intentionally verifies a hard-coded generated source
        // as a snapshot. The source generator is not implemented yet, so this
        // test will fail (creating a .received.txt) until the generator output
        // matches the approved snapshot. This provides the required "Red"
        // snapshot test for the feature plan.

        var generated = @"// <auto-generated />
// Generated lexer for MyLang
namespace MyLang
{
    public enum MyLangTokenType { If, Identifier, EndOfInput }
}
";

        return Verifier.Verify(generated);
    }
}
