using System.Threading.Tasks;
using VerifyXunit;
using Xunit;

[UsesVerify]
public class TokenGeneratorSnapshots
{
    [Fact]
    public Task MinimalGrammar_GeneratesCode()
    {
        // Placeholder generated output. The real generator will replace this.
        var generated = @"// <auto-generated />
    // Generated lexer for MyLang
    namespace MyLang
    {
        public enum MyLangTokenType { If, Identifier, EndOfInput }
    }
    ";

        // Verify snapshot — this will surface as a failing snapshot test until
        // the generator produces the expected output.
        return Verifier.Verify(generated);
    }
}
